---
  - name: Wait 600 seconds for target connection to become reachable/usable
    wait_for_connection:

  - name: Add kubernetes repos
    yum_repository:
      name: kubernetes
      description: Kubernetes Repo
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled: yes
      gpgcheck: yes
      repo_gpgcheck: yes
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude: kubelet kubeadm kubectl

  - name: Set SELinux to permissive
    selinux:
      policy: targeted
      state: permissive

  - name: Install kubelet,kubeadm,kubectl
    yum:
      disable_excludes: kubernetes
      name:
        - firewalld
        - kubeadm
        - kubelet
        - kubectl
        - docker
        - python-docker

  - name: Enable kubelet and docker service
    service:
      name: "{{ item }}"
      enabled: yes
      state: started
    loop:
      - firewalld
      - docker
      - kubelet

  - name: Login to the docker registry
    docker_login:
      username: "{{ username }}" 
      password: "{{ password }}"

  - name: Disable swap
    shell: |
      swapoff -a
