---
  - hosts: host
    vars_files:
      - ./vars/hypervisor_vars.yml
    tasks:
      - name: Install libvirt packages
        yum:
          name: "{{item}}"
          state: latest
        loop:
          - libvirt-client
          - libvirt-daemon
          - python
          - python-lxml
          - qemu-kvm
          - libvirt-daemon-driver-qemu
          - libvirt-daemon-kvm
          - virt-install
          - bridge-utils
          - libguestfs-tools
          - net-tools
          - libguestfs-xfs
          - net-tools
          - python-setuptools
          - wget
          - python3

      - name: Starting libvirtd service
        systemd:
          name: libvirtd
          state: started

      - name: Enabling libvirtd
        systemd:
          name: libvirtd
          enabled: yes

      - name: Create /home/images dir
        file:
          path: /home/images
          state: directory
          mode: '0755'

      - name: Remove images directory
        file:
          path: /var/lib/libvirt/images
          state: absent

      - name: Creating softlinks for /home/images
        file:
          dest: /var/lib/libvirt/images
          src: /home/images
          state: link

      - name: Define default network
        virt_net:
          command: define
          name: "{{item.network_name}}"
          xml: "{{ lookup('template', 'files/' + item.network_file) }}"
        loop:
          - network_name: default
            network_file: network.xml.j2

      - name: Start default network
        virt_net:
          command: start
          name: "{{ item }}"
        loop:
          - default

      - name: Autostart default network
        virt_net:
          autostart: yes
          name: "{{ item }}"
        loop:
          - default
