---
  - name: Configure KVM host
    hosts: host
    vars_files:
      - ./vars/hypervisor_vars.yml
      - ./vars/node_vars.yml
    tasks:
      - name: Install pkgs and pull centos image
        include_tasks: setup_hypervisor.yml
    
      - name: Spawn VMs to setup k8s cluster nodes
        include_tasks: setup_nodes.yml
    
      - name: Gather ip addresses of cluster nodes
        include_tasks: populate_hosts.yml

  - name: Configure all master & worker nodes
    hosts: all_nodes
    any_errors_fatal: true
    tasks:
      - name: Setup configurations needed on all nodes
        include_tasks: setup_cluster_nodes.yml

  - name: Master node configs
    hosts: master
    any_errors_fatal: true
    vars_files:
      - ./vars/hypervisor_vars.yml
      - ./vars/node_vars.yml
    roles:
      - configure_master

  - name: Setup container networking plugin
    hosts: master
    any_errors_fatal: true
    vars_files:
      - ./vars/cluster_vars.yml
    roles:
      - configure_cni

  - name: Join worker nodes
    hosts: worker
    vars_files:
      - ./vars/hypervisor_vars.yml
      - ./vars/node_vars.yml
    vars:
      - join_cmd: "{{ hostvars[hostvars['localhost']['groups']['master'][0]]['join_cmd']['stdout'] }}"
    roles:
      - configure_worker
