---
  - name: Install pkgs and pull centos image
    import_playbook: setup_hypervisor.yml

  - name: Spawn VMs to setup k8s cluster nodes
    import_playbook: setup_nodes.yml

  - name: Gather ip addresses of cluster nodes
    import_playbook: populate_hosts.yml
