---
  - name: Configure KVM host
    hosts: host
    vars_files:
      - ./vars/hypervisor_vars.yml
      - ./vars/node_vars.yml
    tasks:
      - name: Install pkgs and pull centos image
        include_tasks: setup_hypervisor.yml
    
      - name: Spawn VMs to setup k8s cluster nodes
        include_tasks: setup_nodes.yml
    
      - name: Gather ip addresses of cluster nodes
        include_tasks: populate_hosts.yml

  - name: Configure all master & worker nodes
    hosts: all_nodes
    any_errors_fatal: true
    tasks:
      - name: Setup configurations needed on all nodes
        include_tasks: setup_cluster_nodes.yml
