---
vm_location: "/home/images"

root_pass: "password"

nodes:
  master_nodes: 1
  master_node_format: "master-"
  worker_nodes: 2
  worker_node_format: "worker-"

master_specs:
  mem: 10240
  cpus: 5
  os_type: rhel7
  file_type: qcow2

worker_specs:
  mem: 10240
  cpus: 5
  os_type: rhel7
  file_type: qcow2
