apiVersion: v1
kind: Pod
metadata:
  name: check-pod
  labels:
    app: check-pod
spec:
  volumes:
  - name: pod-volume
    hostPath: 
      path: /root/pod-volume
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: pod-volume
