apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mynginx
  template:
    metadata:
      labels:
        name: mynginx
    spec:
      containers:
      - name: yadnesh-nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 443

