---
# tasks file for roles/configure_cni
- name: Check for an existing CNI plugin
  shell: |
    kubectl --kubeconfig={{ kubeadmin_config }} get ds -A | grep {{ cni_plugin }}
  register: check_cniplugin
  run_once: true
  ignore_errors: true

- name: Create {{ cni_plugin }} daemon set
  shell: |
    export kubever=$(kubectl version | base64 | tr -d '\n')
    kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$kubever"
  when: cni_plugin == "weave" and check_cniplugin.failed
