# Avoid setting LimitRange constraints that are too high, or ResourceQuota
# constraints that are too low. A violation of LimitRange constraints prevents pod
# creation, resulting in error messages. A violation of ResourceQuota constraints
# prevents a pod from being scheduled to any node. The pod might be created but
# remain in the pending state.

---
# Quotas are applied to new resources, they do not affect
# the existing resources.
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
spec:
  hard:
    pods: 6 #if already 3 pods are running, this will not scale down 1 pod

---
# Define min,default & max values for resources
apiVersion: v1
kind: LimitRange
metadata:
  name: limit-range
spec:
  limits:
    - type: Pod
      max:
        cpu: "500m"
        memory: "750Mi"
      min:
        cpu: "10m"
        memory: "5Mi"
